# Aquarius - Automation Simplified
#
# @brief Git script for exporting PCB data for Servo Module
# @note runs manually or automatically when there is a release
# @date 6/11/25
# @author cyberreefguru
# (c) CRG Makes 2025
name: Aquarius-Servo-Module-Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  call-export-pcb:
    uses: crgmakes/kicad-extras/.github/workflows/aquarius-pcb-release.yaml@main
    with:
      repo-name: module-servo
      file-name: servo-module
